;; device 
(entry_a0 1)
(entry_a1 1)
( io_c_a0 1)
( io_i_a0 1)
(io_oe_a0 1)
;; basic 
(quit () #xffff D?JMP)
(const (n) n D=A)
(eval (s) s D=M)
(set (s e) e s M=D)
(1- (s) s D=M-1)
(1+ (s) s D=M+1)
(decf (s) (1- s) M=D)
(incf (s) (1+ s) M=D)
(+ (a b) a D=M b D=D+M)
(- (a b) a D=M b D=D-M)
(jeq (s e v) e v D=D-A s D?JEQ)
(jne (s e v) e v D=D-A s D?JNE)
(jgt (s e v) e v D=D-A s D?JGT)
(jge (s e v) e v D=D-A s D?JGE)
(jlt (s e v) e v D=D-A s D?JLT)
(jle (s e v) e v D=D-A s D?JLE)
(jmp (s e v) e v D=D-A s D?JMP)
(<< (n k) n k D=D<<A)
(1<< (k) k D=A 1 D=A<<D)
(0<< (k) k D=A 1 D=A!<<D)
;; stack 
(sp 1)
