;; dev section 
(    page_a0 1)
(   entry_a0 1)
(   entry_a1 1)
(   io_os_a0 1)
(   io_is_a0 1)
(    io_c_a0 1)
(    io_c_a1 1)
(    io_c_a2 1)
(    io_c_a3 1)
(    io_c_a4 1)
(    io_c_a5 1)
(    io_c_a6 1)
(    io_c_a7 1)
(    io_i_a0 1)
(    io_i_a1 1)
(    io_i_a2 1)
(    io_i_a3 1)
(    io_i_a4 1)
(    io_i_a5 1)
(    io_i_a6 1)
(    io_i_a7 1)
(   io_oe_a0 1)
(   io_oe_a1 1)
(   io_oe_a2 1)
(   io_oe_a3 1)
(   io_oe_a4 1)
(   io_oe_a5 1)
(   io_oe_a6 1)
(   io_oe_a7 1)
(   io_ie_a0 1)
(   io_ie_a1 1)
(   io_ie_a2 1)
(   io_ie_a3 1)
(   io_ie_a4 1)
(   io_ie_a5 1)
(   io_ie_a6 1)
(   io_ie_a7 1)
(     cnt_a0 1)
(     cnt_a1 1)
(     cnt_a2 1)
(     cnt_a3 1)
(     cnt_a4 1)
(     cnt_a5 1)
(     cnt_a6 1)
(     cnt_a7 1)
( tmr_sel_a0 1)
( tmr_set_a0 1)
(tmr_from_a0 1)
(     tmr_a0 1)
;; basic 
(quit () #xffff C0?JMP)
(const (n) n D=A)
(eval (s) s D=M)
(set (s e) e s M=D)
(1- (s) s D=M-1)
(1+ (s) s D=M+1)
(decf (s) (1- s) M=D)
(incf (s) (1+ s) M=D)
(or (a b) a D=M b D=DVM)
(and (a b) a D=M b D=D&M)
(+ (a b) a D=M b D=D+M)
(- (a b) a D=M b D=D-M)
(jeq (s e v) e v D=D-A s D?JEQ)
(jne (s e v) e v D=D-A s D?JNE)
(jgt (s e v) e v D=D-A s D?JGT)
(jge (s e v) e v D=D-A s D?JGE)
(jlt (s e v) e v D=D-A s D?JLT)
(jle (s e v) e v D=D-A s D?JLE)
(jmp (s e v) e v D=D-A s D?JMP)
(<< (n k) n k D=D<<A)
(1<< (k) k D=A 1 D=A<<D)
(0<< (k) k D=A 1 D=A!<<D)
;; stack 
(sp 1)
;; counter 
(nop (e) e (_nop) _nop D=D-1?JGT (_nop ()))
(wait (k)
 (set tmr_from_a0 k)
 (set tmr_set_a0 (const 1)) (_wait) (eval tmr_set_a0) _wait D?JEQ (_wait ())
 (_wait) (eval tmr_a0) _wait D?JNE (_wait ())
 (set tmr_set_a0 (const 0)) (_wait) (eval tmr_set_a0) _wait D?JNE (_wait ())
)
;; uart
(baud 1)
(uart_k 1)
(uart_c 1)
(putc (c) 
  (set uart_c c)
  (set io_i_a0 (const 0)) (wait (eval baud));(nop (eval baud))
  (set io_i_a0 (eval uart_c)) (wait (eval baud)) ;(nop (eval baud))
  (set uart_k (const 7)) (_putc) 
  (set io_i_a0 (<< (eval io_i_a0) -1))
  (wait (eval baud)) ;(nop (eval baud))
  (decf uart_k) _putc D?JGT (_putc ())
  (set io_i_a0 (const 1)) (wait (eval baud)) ;(nop (eval baud))
  )
(getc ()
  (_getc_rx0) (eval io_c_a0) _getc_rx0 D?JNE (_getc_rx0 ())
  (set uart_c (const 0))
  (wait (<< (eval baud) -2)) ;(nop (<< (eval baud) -2))
  (set uart_k (const 8)) (_getc) 
  (wait (eval baud)) ;(nop (eval baud))
  (<< (eval uart_c) 1) io_c_a0 D=DVM uart_c M=D 
  (decf uart_k) _getc D?JGT (_getc ())
  (const 8) uart_c D=M^<<D M=D)
