;; dev section 
(entry_a0 1)
(entry_a1 1)
( io_c_a0 1)
( io_i_a0 1)
(io_oe_a0 1)
;; basic 
(quit () #xffff D?JMP)
(const (n) n D=A)
(eval (s) s D=M)
(set (s e) e s M=D)
(1- (s) s D=M-1)
(1+ (s) s D=M+1)
(decf (s) (1- s) M=D)
(incf (s) (1+ s) M=D)
(or (a b) a D=M b D=DVM)
(and (a b) a D=M b D=D&M)
(+ (a b) a D=M b D=D+M)
(- (a b) a D=M b D=D-M)
(jeq (s e v) e v D=D-A s D?JEQ)
(jne (s e v) e v D=D-A s D?JNE)
(jgt (s e v) e v D=D-A s D?JGT)
(jge (s e v) e v D=D-A s D?JGE)
(jlt (s e v) e v D=D-A s D?JLT)
(jle (s e v) e v D=D-A s D?JLE)
(jmp (s e v) e v D=D-A s D?JMP)
(<< (n k) n k D=D<<A)
(1<< (k) k D=A 1 D=A<<D)
(0<< (k) k D=A 1 D=A!<<D)
;; stack 
(sp 1)
;; counter 
(nop (e) e (_nop) _nop D=D-1?JGT)
(wait_cnt 1)
(wait (k j)
 (set wait_cnt j)
 (_wait)
 (nop k)
 (set wait_cnt (1- wait_cnt))
 (eval wait_cnt)
 _wait
 D?JGT)
(wait1_cnt 1)
(wait1 (k j l)
 (set wait1_cnt l)
 (_wait1)
 (wait k j)
 (set wait1_cnt (1- wait1_cnt))
 (eval wait1_cnt)
 _wait1
 D?JGT)
(wait2_cnt 1)
(wait2 (k j l m)
 (set wait2_cnt l)
 (_wait2)
 (wait1 k j l)
 (set wait2_cnt (1- wait2_cnt))
 (eval wait2_cnt)
 _wait2
 D?JGT)
;; uart
(baud 1)
(tx (c) 
  (set io_i_a0 (const 0)) (nop (eval baud))
  (set io_i_a0 c) (nop (eval baud))
  ((k (1 2 3 4 5 6 7))
    (set io_i_a0 (<< (eval io_i_a0) -1))
    (nop (eval baud))
    )
  (set io_i_a0 (const 1)) (nop (eval baud))
  )
